version: '3.0'
services:
  node:
    build: ./app
    restart: on-failure
    environment:
      - PORT=${PORT}
    scale: 2
    
  nginx:
    build: ./nginx
    container_name: nginx
    restart: on-failure
    environment:
      - PORT=${PORT}
    ports:
      - "80:80"
    depends_on:
      - node

