version: '3.0'
services:
  node:
    build: ./app
    restart: on-failure
    container_name: node
    environment:
      - PORT=${PORT}
  nginx:
    build: ./nginx
    restart: on-failure
    environment:
      - PORT=${PORT}
    ports:
      - "80:${PORT}"

